draw_set_halign(fa_center)
draw_set_color(c_white)
draw_set_alpha(image_alpha)
var font = font_add_sprite_ext(spr_damageFont,"0123456789A",true,0)
draw_set_font(font)
draw_set_color(color)
draw_text_transformed(x,y,text,image_xscale,image_yscale,image_angle)
draw_set_halign(fa_left)
draw_set_color(c_black)
draw_set_alpha(1)